development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb+srv://Dinesh13794:Dinesh1379413794@cluster0.mongodb.net/?retryWrites=true&w=majority' %>
      options:
        server_selection_timeout: 5


development:
  clients:
    default:
      database: task_management_development
      hosts:
        - localhost:27017
      